customfieldsettings:
    getCustomFieldSettingsForPortfolio: >-
        <?php

        require 'php-asana/vendor/autoload.php';


        $client = Asana\Client::accessToken('PERSONAL_ACCESS_TOKEN');


        $result = $client->customfieldsettings->getCustomFieldSettingsForPortfolio($portfolio_gid, array('param' => 'value', 'param' => 'value'), array('opt_pretty' => 'true'))
    getCustomFieldSettingsForProject: >-
        <?php

        require 'php-asana/vendor/autoload.php';


        $client = Asana\Client::accessToken('PERSONAL_ACCESS_TOKEN');


        $result = $client->customfieldsettings->getCustomFieldSettingsForProject($project_gid, array('param' => 'value', 'param' => 'value'), array('opt_pretty' => 'true'))
